[platformio]
default_envs = esp32dev

[env]
  platform = espressif32
  board = esp32dev
  framework = arduino
  monitor_speed = 115200

[env:esp32dev]
build_src_filter = +<*> -<d2_blink_test.cpp>

[env:d2test]
build_src_filter = -<*> +<d2_blink_test.cpp>
